### ISSUE TITLE
merge other modules in

### ISSUE THREAD

**Issue by ftalbrecht** [dune-community/dune-xt#1]
I started to prepare branches in the other modules, but stopped when merging. Go ahead if you like, @renefritze, I do not have anything prepared locally atm...

**Comment by renefritze** [comment]
Yes. Please don't do anything.

**Comment by renefritze** [comment]
My current plan is:

 1. Dry-run the merge stuff
 1. Transfer all issues from dune-xt-{common,grid,la,functions} to here
 1. Set dune-xt-{common,grid,la,functions} archived, making them read-only
 1. Do the actual merge stuff
 1. Profit.

**Comment by tobiasleibner** [comment]
It might be a good idea to go over the issues in the other modules before transfering them here, probably some of them are not relevant anymore.

**Comment by renefritze** [comment]
I don't think that's especially necessary. I've automated clicking the "transfer issue" button with selenium, so I'll just be moving over all open and closed tickets anyway. Doesn't really matter if some get closed afterwards or before.

**Comment by ftalbrecht** [comment]
> Yes. Please don't do anything.

I can do that! Apart from that: sounds good, go ahead!

**Comment by tobiasleibner** [comment]
This is done now.

**Comment by ftalbrecht** [comment]
dune-pybindxi is still missing...

**Comment by tobiasleibner** [comment]
Now also dune-pybindxi is merged, see https://zivgitlab.uni-muenster.de/ag-ohlberger/dune-community/dune-xt/-/merge_requests/6.
