### ISSUE TITLE
numeric_cast is slow

### ISSUE THREAD

**Issue by ftalbrecht** [dune-community/dune-xt#13]
As investigated by @tobiasleibner in https://github.com/dune-community/dune-gdt/pull/170. Maybe we should add an option to replace this by an assert and a `static_cast` if some `DISABLE_ALL_CHECKS` is set.

**Comment by renefritze** [comment]
I don't see any reference to `numeric_cast` in that link?

**Comment by ftalbrecht** [comment]
On 08.10.19 14:21, René Fritze wrote:
> I don't see any reference to `numeric_cast` in that link?

Its hidden in one of the resolved discussions:
https://github.com/dune-community/dune-gdt/pull/170#discussion_r328713030

**Comment by tobiasleibner** [comment]
Moved to gitlab repository.
