### ISSUE TITLE
Fix 'no space left on device' issue on CI

### ISSUE THREAD

**Issue by tobiasleibner** [dune-community/dune-xt#14]
CI currently fails with 'no space left on device' errors for the gcc flavors, clang still succeeds. Building ``test_binaries`` with ``gcc-debug`` opts results in a 33 GB build folder, using clang gives 19 GB. The machines on Azure only guarantee [10 GB](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#capabilities-and-limitations). The actual available storage seems to between 20 and 30 GB. Apparently, the available storage used to be higher up until a few weeks ago which is why the gcc builds used to succeed.

I discussed with @renefritze, he already has most of the infrastructure in place to compile and run the tests on a per-directory-basis such that we do not have to store all test binaries at once and will implement this soon.

**Comment by renefritze** [comment]
> I discussed with @renefritze, he already has most of the infrastructure in place to compile and run the tests on a per-directory-basis such that we do not have to store all test binaries at once and will implement this soon.

I'll get to this and moving issues next week.

Did you also run the tests and the coverage generation script, @tobiasleibner ?

**Comment by tobiasleibner** [comment]
No I didn't. I also didn't build in the test docker environment, so my numbers may not be accurate, but they should at least reflect the trend.

**Comment by tobiasleibner** [comment]
Fixed by #18.
