### ISSUE TITLE
Consider building shared libraries by default

### ISSUE THREAD

**Issue by tobiasleibner** [dune-community/dune-xt#15]
Given our CI storage problems #14, using shared libraries instead of static ones can help reduce binary sizes (33 GB -> 20 GB after compiling all tests). I fixed a few issues with the shared libraries in #10, the only remaining issue I know of is https://github.com/dune-community/dune-pybindxi/pull/13.

**Comment by renefritze** [comment]
I'm fine with this.

**Comment by tobiasleibner** [comment]
Okay, adding ``-DBUILD_SHARED_LIBS=TRUE`` to the ``travis.common`` opt should suffice, or do I have to change something somewhere else?

**Comment by renefritze** [comment]
> do I have to change something somewhere else?

Not that I'm aware of

**Comment by tobiasleibner** [comment]
Should be fixed, see https://github.com/dune-community/config.opts/commit/ec050290cb3b4c7a744a166e91926cbc0aea7a36.

**Comment by tobiasleibner** [comment]
Unfortunately, the build failures due to insufficient disk space #14  also happen in the super module, see [this build](https://dev.azure.com/dune-community/dune-xt-super/_build/results?buildId=987&view=results).

**Comment by tobiasleibner** [comment]
Should be fixed now.
