### ISSUE TITLE
add PETSc as la backend

### ISSUE THREAD

**Issue by ftalbrecht** [dune-community/dune-xt#22]
I talked to Stefano Zampini today about what it takes to add bindings to PETSc matrices, vectors and solvers.
Apart from the fact that PETSc thinks differently of matrices/operators than dune does, I think we do want to have these bindings at some point (much of the solver knowledge seems to clustered around PETSc these days).

Here are just some points I took away from the meeting, for later (self)-reference:
* PETSc needs a local to global DoF mapping, local means per rank, global means over all ranks
* a good starting points is dolfin, i.e.
  - https://github.com/FEniCS/dolfinx/tree/master/cpp/dolfin/la
  - https://github.com/FEniCS/dolfinx/blob/master/cpp/dolfin/fem/utils.cpp
* the sparsity pattern is global, we need to account for that
* the local-to-global map should be similar to what we currently do for the istl amg
* matrices have to be finalized before usage in solvers, set matassemblybegin/end flags
* there are several matrix types, the on of interest could be [MATIS](https://www.mcs.anl.gov/petsc/petsc-current/docs/manualpages/Mat/MATIS.html)
* some of our methods translate
  - rows/cols -> size of local/global map (our rows/cols are local sizes in the PETSc sense, not sure if that translates well)
  - add_to_entry -> matsetvalueslocal
  - mv -> matmult
  - scal -> matscal
  - axpy -> mataxpy
  - unit_row/unit_col -> matzerorowslocal/matzerorowslocalcolumns
* usually one has to call the same kind of function for each matrix type, only one of these will succeed. So always check the return code

**Comment by tobiasleibner** [comment]
Moved to gitlab repository.
